apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::151211569424:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1SKO8RZJ0WDXC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::151211569424:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-28T14:23:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1608"
  uid: 6af809f7-8542-42ae-aa43-2eee6a8ce2e6
